package main

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"

	"github.com/google/go-github/v24/github"
	"github.com/peterbourgon/ff/v3/ffcli"
)

// @Deprecated
func propJSONCmd() *ffcli.Command {
	return &ffcli.Command{
		Name:      "propJSON",
		ShortHelp: "propJSON has been deprecated, use `govbox proposal text` instead",
		Exec: func(ctx context.Context, args []string) error {
			return flag.ErrHelp
		},
	}
}

func proposalCmd() *ffcli.Command {
	return &ffcli.Command{
		Name:      "proposal",
		ShortHelp: "Prints JSON format compatible with the `tx gov submit-proposal` command",
		Subcommands: []*ffcli.Command{
			proposalTextCmd(), proposalAmendmentCmd(), proposalAmendmentDiffCmd(), proposalUpgradeCmd(),
			proposalFillCmd(),
		},
		Exec: func(ctx context.Context, args []string) error {
			return flag.ErrHelp
		},
	}
}

func proposalTextCmd() *ffcli.Command {
	fs := flag.NewFlagSet("text", flag.ContinueOnError)
	deposit := fs.String("deposit", "512000000uatone", "Proposal deposit")
	return &ffcli.Command{
		Name:       "text",
		ShortUsage: "govbox proposal text <path/to/proposal.md>",
		ShortHelp:  "Prints a text proposal for the `tx gov submit-proposal` command",
		FlagSet:    fs,
		Exec: func(ctx context.Context, args []string) error {
			if err := fs.Parse(args); err != nil {
				return err
			}
			if fs.NArg() != 1 {
				return flag.ErrHelp
			}
			summary, err := readProposalSummary(fs.Arg(0))
			if err != nil {
				return err
			}
			// Fetch title from markdown
			title := strings.SplitN(summary, "\n", 2)[0]
			title = title[2:] // Remove the '# ' prefix

			data := map[string]any{
				"title":    title,
				"summary":  summary,
				"deposit":  *deposit,
				"metadata": "ipfs://CID",
			}
			return printPropopal(data)
		},
	}
}

func proposalFillCmd() *ffcli.Command {
	fs := flag.NewFlagSet("fill", flag.ContinueOnError)
	title := fs.String("title", "", "Proposal title. If not provided, the title of the JSON file is kept")
	return &ffcli.Command{
		Name:       "fill",
		ShortUsage: "govbox proposal fill <path/to/proposal.json> <path/to/proposal.md>",
		ShortHelp:  "Fills the summary of an existing proposal JSON file with a markdown file",
		LongHelp: `The proposal JSON file is updated in place: its summary field is replaced by the
content of the markdown file. The title field is set from the -title flag if
provided, else it is left untouched, unless it is missing or empty, in which
case it is read from the first '# ' heading of the markdown file.

The order and the formatting of the other fields are preserved.`,
		FlagSet: fs,
		Exec: func(ctx context.Context, args []string) error {
			if err := fs.Parse(args); err != nil {
				return err
			}
			if fs.NArg() != 2 {
				return flag.ErrHelp
			}
			var (
				propFile = fs.Arg(0)
				descFile = fs.Arg(1)
			)
			bz, err := os.ReadFile(propFile)
			if err != nil {
				return err
			}
			summary, err := readProposalSummary(descFile)
			if err != nil {
				return err
			}
			newTitle := *title
			if newTitle == "" {
				var data struct {
					Title string `json:"title"`
				}
				if err := json.Unmarshal(bz, &data); err != nil {
					return err
				}
				newTitle = data.Title
			}
			if newTitle == "" {
				// No title in the JSON file, fetch it from the markdown.
				heading := strings.SplitN(summary, "\n", 2)[0]
				if !strings.HasPrefix(heading, "# ") {
					return fmt.Errorf("%s has no title and %s doesn't start with a '# ' heading, use the -title flag", propFile, descFile)
				}
				newTitle = heading[2:] // Remove the '# ' prefix
			}
			bz, err = setJSONFields(bz, [][2]string{{"title", newTitle}, {"summary", summary}})
			if err != nil {
				return err
			}
			if err := os.WriteFile(propFile, bz, 0o644); err != nil {
				return err
			}
			fmt.Printf("%s summary updated with the content of %s\n", propFile, descFile)
			return nil
		},
	}
}

func proposalAmendmentCmd() *ffcli.Command {
	fs := flag.NewFlagSet("amendment", flag.ContinueOnError)
	deposit := fs.String("deposit", "512000000uatone", "Proposal deposit")
	return &ffcli.Command{
		Name:       "amendment",
		ShortUsage: "govbox proposal amendment <path/to/amendment.json>",
		ShortHelp:  "Prints a constitution amendment proposal for the `tx gov submit-proposal` command",
		LongHelp:   "The argument must be the file generated by `tx gov generate-constitution-amendment` command.",
		FlagSet:    fs,
		Exec: func(ctx context.Context, args []string) error {
			if err := fs.Parse(args); err != nil {
				return err
			}
			if fs.NArg() != 1 {
				return flag.ErrHelp
			}
			bz, err := os.ReadFile(fs.Arg(0))
			if err != nil {
				return err
			}
			msg := make(map[string]any)
			if err := json.Unmarshal(bz, &msg); err != nil {
				return err
			}
			msg["@type"] = "/atomone.gov.v1.MsgProposeConstitutionAmendment"

			data := map[string]any{
				"title":    "Constitution Amendment",
				"summary":  "# Constitution Amendment\n\nThis is a proposal to amend the constitution of Atom One.\n\nThe amendment is as follows:\n\n```diff\n" + msg["amendment"].(string) + "\n```",
				"messages": []map[string]any{msg},
				"deposit":  *deposit,
				"metadata": "ipfs://CID",
			}
			return printPropopal(data)
		},
	}
}

func proposalAmendmentDiffCmd() *ffcli.Command {
	fs := flag.NewFlagSet("amendment-diff", flag.ContinueOnError)
	deposit := fs.String("deposit", "512000000uatone", "Proposal deposit")
	return &ffcli.Command{
		Name:       "amendment-diff",
		ShortUsage: "govbox proposal amendment-diff <path/to/amendment.diff>",
		ShortHelp:  "Prints a constitution amendment proposal for the `tx gov submit-proposal` command",
		LongHelp:   "The argument must be a patch/diff file",
		FlagSet:    fs,
		Exec: func(ctx context.Context, args []string) error {
			if err := fs.Parse(args); err != nil {
				return err
			}
			if fs.NArg() != 1 {
				return flag.ErrHelp
			}
			bz, err := os.ReadFile(fs.Arg(0))
			if err != nil {
				return err
			}

			data := map[string]any{
				"title":   "Constitution Amendment",
				"summary": "# Constitution Amendment\n\nThis is a proposal to amend the constitution of Atom One.\n\nThe amendment is as follows:\n\n```diff\n" + string(bz) + "\n```",
				"messages": []map[string]any{
					{
						"@type":     "/atomone.gov.v1.MsgProposeConstitutionAmendment",
						"authority": "atone10d07y265gmmuvt4z0w9aw880jnsr700j5z0zqt",
						"amendment": string(bz),
					},
				},
				"deposit":  *deposit,
				"metadata": "ipfs://CID",
			}
			return printPropopal(data)
		},
	}
}

func proposalUpgradeCmd() *ffcli.Command {
	fs := flag.NewFlagSet("upgrade", flag.ContinueOnError)
	deposit := fs.String("deposit", "512000000uatone", "Proposal deposit")
	height := fs.String("height", "0", "Halt height")
	plan := fs.String("plan", "", "Plan name. If not provided shorten the tag argument (for example v3.0.0 becomes v3)")
	return &ffcli.Command{
		Name:       "upgrade",
		FlagSet:    fs,
		ShortUsage: "govbox upgrade TAG <path/to/upgrade.md>",
		ShortHelp:  "Prints an upgrade proposal for the `tx gov submit-proposal` command",
		Exec: func(ctx context.Context, args []string) error {
			if err := fs.Parse(args); err != nil {
				return err
			}
			if fs.NArg() != 2 {
				return flag.ErrHelp
			}
			var (
				tag      = fs.Arg(0)
				descFile = fs.Arg(1)
			)
			info, err := cosmovisorBinInfo(tag)
			if err != nil {
				return err
			}
			summary, err := readProposalSummary(descFile)
			if err != nil {
				return err
			}
			if *plan == "" {
				p := tag[:strings.Index(tag, ".")]
				plan = &p
			}
			msg := map[string]any{
				"@type":     "/cosmos.upgrade.v1beta1.MsgSoftwareUpgrade",
				"authority": "atone10d07y265gmmuvt4z0w9aw880jnsr700j5z0zqt",
				"plan": map[string]any{
					"name":                  plan,
					"time":                  "0001-01-01T00:00:00Z",
					"height":                height,
					"info":                  info,
					"upgraded_client_state": nil,
				},
			}
			data := map[string]any{
				"title":    fmt.Sprintf("AtomOne %s Upgrade", *plan),
				"summary":  summary,
				"messages": []map[string]any{msg},
				"deposit":  *deposit,
				"metadata": "ipfs://CID",
			}
			return printPropopal(data)
		},
	}
}

// setJSONFields returns the JSON object bz with the given top-level string
// fields updated (or appended if missing). Unlike a json.Unmarshal followed by
// a json.MarshalIndent, the order and the formatting of the other fields are
// preserved, because their raw bytes are copied verbatim. The indentation of
// the top-level fields is detected from bz, and defaults to 2 spaces.
func setJSONFields(bz []byte, fields [][2]string) ([]byte, error) {
	dec := json.NewDecoder(bytes.NewReader(bz))
	if tok, err := dec.Token(); err != nil {
		return nil, err
	} else if tok != json.Delim('{') {
		return nil, fmt.Errorf("expected a JSON object, got '%v'", tok)
	}
	// Decode the top-level fields, keeping their raw value and their order.
	var (
		keys   []string
		values = make(map[string]json.RawMessage)
		indent = "  "
		offset = dec.InputOffset()
	)
	for dec.More() {
		tok, err := dec.Token()
		if err != nil {
			return nil, err
		}
		key, ok := tok.(string)
		if !ok {
			return nil, fmt.Errorf("expected a JSON object key, got '%v'", tok)
		}
		if len(keys) == 0 {
			// Detect the indentation from the bytes preceding the first key.
			if gap := string(bz[offset:dec.InputOffset()]); strings.Contains(gap, "\n") {
				gap = gap[strings.LastIndex(gap, "\n")+1:]
				indent = gap[:strings.Index(gap, `"`)]
			}
		}
		var value json.RawMessage
		if err := dec.Decode(&value); err != nil {
			return nil, err
		}
		keys = append(keys, key)
		values[key] = value
	}
	// Update the fields, appending those not already present.
	for _, field := range fields {
		key, value := field[0], field[1]
		if _, ok := values[key]; !ok {
			keys = append(keys, key)
		}
		bz, err := json.Marshal(value)
		if err != nil {
			return nil, err
		}
		values[key] = bz
	}
	var out bytes.Buffer
	out.WriteString("{\n")
	for i, key := range keys {
		if i > 0 {
			out.WriteString(",\n")
		}
		fmt.Fprintf(&out, "%s%q: %s", indent, key, values[key])
	}
	out.WriteString("\n}\n")
	return out.Bytes(), nil
}

func readProposalSummary(path string) (string, error) {
	bz, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	d := string(bz)
	if len(d) > 10000 {
		return "", fmt.Errorf("Description has more than 10000 characters (%d)", len(d))
	}
	return d, nil
}

func cosmovisorBinInfo(tag string) (string, error) {
	// fetch release assets
	client := github.NewClient(nil)
	const (
		owner = "atomone-hub"
		repo  = "atomone"
	)
	rr, _, err := client.Repositories.GetReleaseByTag(context.Background(), owner, repo, tag)
	if err != nil {
		return "", err
	}
	var (
		expectedPrefix = fmt.Sprintf("atomoned-%s-", tag)
		binaries       = make(map[string]string)
		checksumFile   = fmt.Sprintf("SHA256SUMS-%s.txt", tag)
		checksums      = make(map[string]string)
	)
	// loop on assets to fill the checksums
	for _, a := range rr.Assets {
		if a.GetName() != checksumFile {
			continue
		}
		// fetch checksum file
		resp, err := http.Get(a.GetBrowserDownloadURL())
		// r, _, err := client.Repositories.DownloadReleaseAsset(context.Background(), owner, repo, a.GetID())
		if err != nil {
			return "", err
		}
		defer resp.Body.Close()
		r := bufio.NewReader(resp.Body)
		for {
			line, _, err := r.ReadLine()
			if err != nil {
				if err == io.EOF {
					break
				}
				return "", err
			}
			// parse line
			var (
				checksum string
				binary   string
			)
			_, _ = fmt.Sscanf(string(line), "%s %s", &checksum, &binary)
			checksums[binary] = checksum
		}
		break
	}
	// loop on binary assets
	for _, a := range rr.Assets {
		if strings.HasPrefix(expectedPrefix, a.GetName()) {
			continue
		}
		value := a.GetBrowserDownloadURL() + "?checksum=sha256:" + checksums[a.GetName()]
		switch a.GetName()[len(expectedPrefix):] {
		case "darwin-amd64":
			binaries["darwin/amd64"] = value
		case "linux-amd64":
			binaries["linux/amd64"] = value
		case "darwin-arm64":
			binaries["darwin/arm64"] = value
		case "linux-arm64":
			binaries["linux/arm64"] = value
		}
	}
	bz, err := json.Marshal(map[string]any{"binaries": binaries})
	if err != nil {
		return "", err
	}
	return string(bz), nil
}

func printPropopal(data map[string]any) error {
	bz, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return err
	}
	fmt.Println(string(bz))
	return nil
}
